modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/mickelus/mutil/issues"
license="MIT"

[[mods]]
modId="mutil"
version="${file.jarVersion}"
displayName="mutil"
displayURL="https://github.com/mickelus/mutil"
authors="Mickelus"
description='''
View library for minecraft mods.
'''

[[dependencies.mutil]] #optional
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.mutil]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
